
import Grid from "../template/Grid/Grid";

export default function Home() {
  return (
    // <div className={styles.container}>
    //   <style jsx>
    //     {`
    //       h2 {
    //         font-size: 38px;
    //       }
    //       h3 {
    //         font-size: 28px;
    //       }
    //     `}
    //   </style>

    //   <Head>
    //     <title>Hunting Coder </title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>Hunting Coder</h1>
    //     <div className={styles.Imgrape}>
    //       <Image
    //         className={styles.myImg}
    //         src="/image.jpg"
    //         alt="image"
    //         width={237}
    //         height={158}
    //       />
    //     </div>
    //     <p className={styles.description}>Welcome To my Blog</p>
    //     <div className="blogs">
    //       <h2>Popular Blogs</h2>
    //       <div className="blogItem">
    //         <h3>How to learn NextJs in 2022</h3>
    //         <p>
    //           Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ut
    //           numquam facilis est.
    //         </p>
    //       </div>
    //       <div className="blogItem">
    //         <h3>How to learn NextJs in 2022</h3>
    //         <p>
    //           Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ut
    //           numquam facilis est.
    //         </p>
    //       </div>
    //       <div className="blogItem">
    //         <h3>How to learn NextJs in 2022</h3>
    //         <p>
    //           Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ut
    //           numquam facilis est.
    //         </p>
    //       </div>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}></footer>
    // </div>
    <>
   {/* {content.map((item, index) => (
            <Grid key={index} item={item} />
          ))} */}
          <Grid/>
    </>
  );
}
